/**
 * Demo Profiles Configuration
 * Auto-generated by create-demo-profiles.js
 * Generated on: 2025-10-29T00:16:43.308Z
 */

module.exports = {
  baseUrl: 'https://unterrified-bea-prolately.ngrok-free.dev',
  profiles: [
  {
    "name": "Matt",
    "sessionId": "DEMO_USER_1",
    "profileCode": "P4ZHPYAG",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/P4ZHPYAG",
    "photoCount": 2
  },
  {
    "name": "Jimmy",
    "sessionId": "DEMO_USER_2",
    "profileCode": "H72ND45W",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/H72ND45W",
    "photoCount": 2
  },
  {
    "name": "Landon",
    "sessionId": "DEMO_USER_3",
    "profileCode": "TWPC8LTP",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/TWPC8LTP",
    "photoCount": 2
  },
  {
    "name": "Sai",
    "sessionId": "DEMO_USER_4",
    "profileCode": "TR7MZP4Y",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/TR7MZP4Y",
    "photoCount": 2
  }
]
};
