/**
 * Demo Profiles Configuration
 * Auto-generated by create-demo-profiles.js
 * Generated on: 2025-10-29T10:25:20.242Z
 */

module.exports = {
  baseUrl: 'https://unterrified-bea-prolately.ngrok-free.dev',
  profiles: [
  {
    "name": "Matt",
    "sessionId": "DEMO_USER_1",
    "profileCode": "NT8CC4UV",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/NT8CC4UV",
    "photoCount": 2
  },
  {
    "name": "Jimmy",
    "sessionId": "DEMO_USER_2",
    "profileCode": "AVG955TG",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/AVG955TG",
    "photoCount": 2
  },
  {
    "name": "Landon",
    "sessionId": "DEMO_USER_3",
    "profileCode": "RHTZ5V2W",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/RHTZ5V2W",
    "photoCount": 2
  },
  {
    "name": "Sai",
    "sessionId": "DEMO_USER_4",
    "profileCode": "2BX2Q6DJ",
    "profileUrl": "https://unterrified-bea-prolately.ngrok-free.dev/profile/2BX2Q6DJ",
    "photoCount": 2
  }
]
};
